spring:
 datasource:
   url: ${DATASOURCE_URL}
   username: ${DATASOURCE_USER}
   password: ${DATASOURCE_PASSWORD}
   driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
 jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect    
 mvc:
   pathmatch:
     matching-strategy: ant_path_matcher
server:
 port: 8080
frontend:
  url: ${FRONTEND_URL}
  urlFirebase: ${FRONTEND_URL_FIREBASE}
