spring:
 datasource:
   url: ${DATASOURCE_URL}
   username: ${DATASOURCE_USER}
   password: ${DATASOURCE_PASSWORD}
   driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
 jpa:
    show-sql: true
    hibernate.ddl-auto: update    
 mvc:
   pathmatch:
     matching-strategy: ant_path_matcher
server:
 port: 8080
frontend:
  url: ${FRONTEND_URL}
  urlFirebase: ${FRONTEND_URL_FIREBASE}
