spring:
 datasource:
   url: jdbc:postgresql://dpg-d2hf3aer433s739nm3t0-a.singapore-postgres.render.com/companydb_4c76
   username: mohit
   password: 608VBIv5FVWfEVcM5XzwTCMxVbVwoymv
   driver-class-name: org.postgresql.Driver
 jpa:
    show-sql: true
    hibernate.ddl-auto: update
    hibernate.hbm2ddl.auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.default_schema: public   
 mvc:
   pathmatch:
    matching-strategy: ANT_PATH_MATCHER
 ai:
    openai:
      api-key: ${OPENAI_API_KEY:your_default_api_key}
 autoconfigure:
    exclude:
      - org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration
server.port: ${SERVER_PORT:8080}
corsallowedorigins: http://localhost:4200,https://uiangularapp.web.app
corsallowedmethods: GET,POST,PUT,DELETE,OPTIONS