spring:
 datasource:
   url: jdbc:postgresql://34.131.175.174:5432/companydb
   username: postgres
   password: root
   driver-class-name: org.postgresql.Driver
 jpa:
    show-sql: true
    hibernate.ddl-auto: update
    hibernate.hbm2ddl.auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.default_schema: public   
 mvc:
   pathmatch:
    matching-strategy: ANT_PATH_MATCHER
 ai:
    openai:
      api-key: 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
 autoconfigure:
    exclude:
      - org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration
server.port: ${SERVER_PORT:8080}
corsallowedorigins: http://localhost:4200,https://uiangularapp.web.app
corsallowedmethods: GET,POST,PUT,DELETE,OPTIONS